
configfile: workflow.source_path('../config/snakebids.yml')

localrules: participant, bidsify, group

resource_scopes:
    gpu="local"

include: "rules/setup.smk"
include: "rules/t1_template.smk"
include: "rules/surfaces.smk"
include: "rules/transforms.smk"
include: "rules/qc.smk"


rule participant:
    input:
        inputs["t1w"].expand([
            rules.ciftify_vis.output[0],
            rules.bidsify.output[0],
            rules.convert_transforms_to_h5.output[0],
        ]),
    default_target: True

rule group:
    input:
        rules.ciftify_vis_group.output
